## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [159]:
import pandas as pd

In [160]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [161]:
df = data
result1 = df["sex"].value_counts()
print(result1)

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [162]:
df = data
result2 = df.groupby('sex')['age'].mean().loc['Male']
print(result2)

39.43354749885268

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [163]:
df = data
us_quantity = df['native-country'].value_counts().loc['United-States']
total_quantity = len(df)
result3 = us_quantity/total_quantity

print(result3)

0.895857006848684

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [164]:
df = data
avg_age_over_50K = df.groupby('salary')['age'].mean().loc['>50K']
std_over_50K = df.groupby('salary')['age'].std().loc['>50K']
avg_age_under_50K = df.groupby('salary')['age'].mean().loc['<=50K']
std_under_50K = df.groupby('salary')['age'].std().loc['<=50K']

print("Average age for salary over 50K:", avg_age_over_50K)
print("Average age for salary under 50K:", avg_age_under_50K)
print("Standard deviation on age for salary over 50K:", std_over_50K)
print("Standard deviation on age for salary under 50K:", std_under_50K)

Average age for salary over 50K: 44.24984058155847
Average age for salary under 50K: 36.78373786407767
Standard deviation on age for salary over 50K: 10.519027719851843
Standard deviation on age for salary under 50K: 14.020088490824866

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [165]:
df = data
higher_edu = [
    'Bachelors', 'Prof-school', 'Assoc-acdm',
    'Assoc-voc', 'Masters', 'Doctorate'
]
total_over_50K = df['salary'].value_counts().loc['>50K']
high_edu_for_over_50K = df[df['salary']=='>50K'].loc[df['education'].isin(higher_edu), 'education'].value_counts()
total_high_edu_for_over_50K = df[df['salary']=='>50K'].loc[df['education'].isin(higher_edu), 'education'].count()
perc_high_edu_over_50K = high_edu_for_over_50K/total_over_50K*100

print("High education percentage for salary over 50K:", total_high_edu_for_over_50K/total_over_50K*100)
print()

print("Percentage per degree for salary over 50K", perc_high_edu_over_50K)

print("Большинство людей (57%) с зп свыше 50К имеют минимум высшее образование")

High education percentage for salary over 50K: 57.83701058538452

Percentage per degree for salary over 50K education
Bachelors      28.325469
Masters        12.230583
Prof-school     5.394720
Assoc-voc       4.604005
Doctorate       3.902563
Assoc-acdm      3.379671
Name: count, dtype: float64
Большинство людей (57%) с зп свыше 50К имеют минимум высшее образование

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [166]:
df = data

stats = df.groupby(['race', 'sex'])['age'].describe()

max_age = stats.loc[('Asian-Pac-Islander', 'Male'), 'max']

print(stats)
print()
print("Максимальный возраст мужчин Asian-Pac-Islander:", max_age)

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

Максимальный возраст мужчин Asian-Pac-Islander: 90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [167]:
df = data
married = ['Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse']

total_married = df[(df['sex'] == 'Male') &  (df['marital-status'].isin(married))]['salary'].count()
total_married_over_50K = df[(df['salary'] == '>50K') & (df['sex'] == 'Male') &  (df['marital-status'].isin(married))]['salary'].count()
married_over_50K_perc = total_married_over_50K/total_married*100

total_not_married = df[(df['sex'] == 'Male') &  (~df['marital-status'].isin(married))]['salary'].count()
total_not_married_over_50K = df[(df['salary'] == '>50K') & (df['sex'] == 'Male') &  (~df['marital-status'].isin(married))]['salary'].count()
not_married_over_50K_perc = total_not_married_over_50K/total_not_married*100


print("Процент зарабатывающих более 50К среди женатых:", married_over_50K_perc)
print("Процент зарабатывающих более 50К среди холостых:", not_married_over_50K_perc)

Процент зарабатывающих более 50К среди женатых: 44.05139945351156
Процент зарабатывающих более 50К среди холостых: 8.449509031397746

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [168]:
df = data
max_hours = df['hours-per-week'].max()
people_with_max_hours = (df['hours-per-week']== max_hours).sum()

people_with_max_hours_over_50K = ((df['hours-per-week']== max_hours) & (df['salary'] == '>50K') ).sum()
perc = people_with_max_hours_over_50K/people_with_max_hours*100

print("Максимальное количество часов в неделю:", max_hours)
print("Количество людей, работающих больше всех:", people_with_max_hours)
print("Процент зарабатывающих более 50К среди трудоголиков:", perc)

Максимальное количество часов в неделю: 99
Количество людей, работающих больше всех: 85
Процент зарабатывающих более 50К среди трудоголиков: 29.411764705882355

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [169]:
df = data
per_country_over_50K = (df[df['salary'] == '>50K'].groupby('native-country')['hours-per-week'].mean()
)

per_country_under_50K = (df[df['salary'] == '<=50K'].groupby('native-country')['hours-per-week'].mean()
)

result = pd.concat(
    [per_country_over_50K, per_country_under_50K],
    axis=1,
    keys=['>50K', '<=50K']
)

print(result)

                                 >50K      <=50K
native-country
?                           45.547945  40.164760
Cambodia                    40.000000  41.416667
Canada                      45.641026  37.914634
China                       38.900000  37.381818
Columbia                    50.000000  38.684211
Cuba                        42.440000  37.985714
Dominican-Republic          47.000000  42.338235
Ecuador                     48.750000  38.041667
El-Salvador                 45.000000  36.030928
England                     44.533333  40.483333
France                      50.750000  41.058824
Germany                     44.977273  39.139785
Greece                      50.625000  41.809524
Guatemala                   36.666667  39.360656
Haiti                       42.750000  36.325000
Honduras                    60.000000  34.333333
Hong                        45.000000  39.142857
Hungary                     50.000000  31.300000
India                       46.475000  38.233333
Iran                        47.500000  41.440000
Ireland                     48.000000  40.947368
Italy                       45.400000  39.625000
Jamaica                     41.100000  38.239437
Japan                       47.958333  41.000000
Laos                        40.000000  40.375000
Mexico                      46.575758  40.003279
Nicaragua                   37.500000  36.093750
Peru                        40.000000  35.068966
Philippines                 43.032787  38.065693
Poland                      39.000000  38.166667
Portugal                    41.500000  41.939394
Puerto-Rico                 39.416667  38.470588
Scotland                    46.666667  39.444444
South                       51.437500  40.156250
Taiwan                      46.800000  33.774194
Thailand                    58.333333  42.866667
Trinadad&Tobago             40.000000  37.058824
United-States               45.505369  38.799127
Vietnam                     39.200000  37.193548
Yugoslavia                  49.500000  41.600000
Holand-Netherlands                NaN  40.000000
Outlying-US(Guam-USVI-etc)        NaN  41.857143

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [173]:
df = data

def get_age_group(age):
    if 16 <= age <= 35:
        return 'young'
    elif 35 < age <= 70:
        return 'adult'
    else:
        return 'retiree'

df['AgeGroup'] = df['age'].apply(get_age_group)

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [184]:
df = data

count_over_50K_by_agegroup = (df[df['salary'] == '>50K'].groupby('AgeGroup')['salary'].count())
top_age_group = count_over_50K_by_agegroup.idxmax()

print(count_over_50K_by_agegroup)
print()
print("Возрастная группа, где чаще всего зарабатывают более 50K:", top_age_group)

AgeGroup
adult      6042
retiree      94
young      1705
Name: salary, dtype: int64

Возрастная группа, где чаще всего зарабатывают более 50K: adult

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [205]:
df = data

occupation_counts = df.groupby('occupation').size()
print(occupation_counts)

def filter_func(group, age=40, hours=5):
    return (group['age'].mean() <= age) and (group['hours-per-week'].min() > hours)

filtered_df = df.groupby('occupation').filter(filter_func)

filtered_counts = filtered_df.groupby('occupation').size()

print()
print("Средний возраст <= 40 и все работают > 5 часов в неделю:")
print(filtered_counts)

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64

Средний возраст <= 40 и все работают > 5 часов в неделю:
occupation
Armed-Forces    9
dtype: int64